@startuml

class FabriqueClasse {
    + createVueClasse(): VueClasse
    + createVueAttribut(): VueAttribut
    + createVueInterface(): VueInterface
    + createVueMethode(): VueMethode
    + createVuePackage(): VuePackage
}

class VueClasse {
    + afficher(): void
}

class VueAttribut {
    + afficher(): void
}

class VueInterface {
    + afficher(): void
}

class VueMethode {
    + afficher(): void
}

class VuePackage {
    + afficher(): void
}

FabriqueClasse --> VueClasse
FabriqueClasse --> VueAttribut
FabriqueClasse --> VueInterface
FabriqueClasse --> VueMethode
FabriqueClasse --> VuePackage

@enduml
